#!/usr/bin/make

# [ Warning ] don't use make to solve dependencies !!
#
# we rely on ocamlbuild which already handles them ; every rule should
# call it only once (no recursion)
#
# More info in build/Makefile.bld

include config.make

INSTALL ?= cp -u -L

.PHONY: default
default: all

include build/Makefile.bld

OPAOPT += "--rebuild"

export

##
## STANDARD TARGETS
##

.PHONY: all
all: $(MYOCAMLBUILD)
	$(OCAMLBUILD) $(call target-tools,$(ALL_TOOLS)) opa-packages.stamp
	@$(call copy-tools,$(ALL_TOOLS))

.PHONY: build
build: all

.PHONY: runtime-libs
runtime-libs: $(MYOCAMLBUILD)
	$(OCAMLBUILD) runtime-libs.stamp

$(BUILD_DIR)/bin/opa: $(MYOCAMLBUILD)
	$(OCAMLBUILD) opa-packages.stamp $(target-tool-opa-bin)
	@$(copy-tool-opa-bin)
	@utils/install.sh --quiet --dir $(PWD)/$(BUILD_DIR) --ocaml-prefix $(OCAMLLIB)/../..

.PHONY: opa
opa: $(BUILD_DIR)/bin/opa

.PHONY: opa-packages
opa-packages: $(MYOCAMLBUILD)
	$(OCAMLBUILD) opa-packages.stamp

.PHONY: stdlib
stdlib: opa-packages

DISTRIB_TOOLS = opa-bin opadoc opa-plugin-builder-bin opa-plugin-browser-bin bslServerLib.ml opa-db-server opa-db-tool opa-cloud

.PHONY: distrib
distrib: $(MYOCAMLBUILD)
	$(OCAMLBUILD) $(call target-tools,$(DISTRIB_TOOLS)) opa-packages.stamp
	@$(call copy-tools,$(DISTRIB_TOOLS))

##
## INSTALLATION
##

.PHONY: install*

STDLIB_DIR = $(PREFIX)/lib/opa/stdlib
define install-package
@echo "Installing into $(STDLIB_DIR)/$*.opx[K\r\c"
@mkdir -p "$(STDLIB_DIR)/$*.opx/_build"
@find "$(BUILD_DIR)/$*.opx" -maxdepth 1 ! -type d -exec $(INSTALL) {} "$(STDLIB_DIR)/$*.opx/" \;
@$(INSTALL) $(BUILD_DIR)/$*.opx/_build/*.a "$(STDLIB_DIR)/$*.opx/_build/"
@$(INSTALL) $(BUILD_DIR)/$*.opx/_build/*.cmi "$(STDLIB_DIR)/$*.opx/_build/"
@$(INSTALL) $(BUILD_DIR)/$*.opx/_build/*.cmxa "$(STDLIB_DIR)/$*.opx/_build/"
endef

OPA_PACKAGES := $(shell cd stdlib && ./all_packages.sh)

# Rules installing everything that has been compiled
#
# This doesn't rely on install rules generated by Makefile.bld ;
# instead it assumes that what you want to install has been properly
# put in $(BUILD_DIR)/{bin,lib/opa,share/opa}.
#
# This is the case of tools (because of Makefile.bld),
# and of opa runtime libs (because build rules copy them
# to $(BUILD_DIR)/lib/opa/static).
# This doesn't install the other libs though, use target install-libs
# for that

install-packageopt-%:
	$(if $(wildcard $(BUILD_DIR)/$*.opx/_build/*),$(install-package))

install-package-%:
	$(install-package)

install-packages: $(addprefix install-packageopt-,$(OPA_PACKAGES))
	@echo "Installation to $(STDLIB_DIR) done.[K"

install-all-packages: $(addprefix install-package-,$(OPA_PACKAGES))
	@echo "Installation to $(STDLIB_DIR) done.[K"

install-bin:
	@echo "Installing into $(PREFIX)/bin[K\r\c"
	@mkdir -p $(PREFIX)/bin
	@$(if $(wildcard $(BUILD_DIR)/bin/*),$(INSTALL) -r $(BUILD_DIR)/bin/* $(PREFIX)/bin)
	@utils/install.sh --quiet --dir $(PREFIX) --ocamllib $(OCAMLLIB) --ocamlopt $(OCAMLOPT)
	@echo "Installation to $(PREFIX)/bin done.[K"

install-lib:
	@echo "Installing into $(PREFIX)/lib/opa[K\r\c"
	@mkdir -p $(PREFIX)/lib/opa
	@$(if $(wildcard $(BUILD_DIR)/lib/opa/*),$(INSTALL) -r $(BUILD_DIR)/lib/opa/* $(PREFIX)/lib/opa/)
	@echo "Installation to $(PREFIX)/lib/opa done.[K"

install-share:
	@echo "Installing into $(PREFIX)/share/opa[K\r\c"
	@mkdir -p $(PREFIX)/share/opa
	@$(if $(wildcard $(BUILD_DIR)/share/opa/*),$(INSTALL) -r $(BUILD_DIR)/share/opa/* $(PREFIX)/share/opa/)
	@echo "Installation to $(PREFIX)/share/opa done.[K"

install-doc:
	@echo "Installing into $(PREFIX)/share/doc/opa[K\r\c"
	@if [ -d $(BUILD_DIR)/opadoc/doc/ ]; then \
	  mkdir -p $(PREFIX)/share/doc/opa/api; \
	  $(INSTALL) -r $(BUILD_DIR)/opadoc/doc/* $(PREFIX)/share/doc/opa/api; \
	fi
	@echo "Installation to $(PREFIX)/share/doc/opa done.[K"

install: install-bin install-lib install-share install-packages install-doc
	@echo "Installation under prefix $(PREFIX) done.[K"

.PHONY: uninstall
uninstall:
	rm -rf $(PREFIX)/lib/opa
	@[ ! -d $(PREFIX)/lib ] || [ -n "`ls -A $(PREFIX)/lib`" ] || rmdir $(PREFIX)/lib
	rm -rf $(PREFIX)/share/opa
	rm -rf $(PREFIX)/share/doc/opa
	@[ ! -d $(PREFIX)/share ] || [ -n "`ls -A $(PREFIX)/share`" ] || rmdir $(PREFIX)/share
	$(foreach file,$(BUILD_DIR)/bin/*,rm -f $(PREFIX)/bin/$(notdir $(file));)
	@utils/install.sh --uninstall --dir $(PREFIX)
	@[ ! -d $(PREFIX)/bin ] || [ -n "`ls -A  $(PREFIX)/bin`" ] || rmdir $(PREFIX)/bin
	@echo "Uninstall done.[K"

# Install our ocamlbuild-generation engine
install-bld:
	@mkdir -p $(PREFIX)/bin
	@echo "#!/bin/bash -ue" > $(PREFIX)/bin/bld
	@chmod 755 $(PREFIX)/bin/bld
	@echo "BLDDIR=$(PREFIX)/share/opa/bld $(PREFIX)/share/opa/bld/gen_myocamlbuild.sh" >> $(PREFIX)/bin/bld
	@echo "_build/myocamlbuild -no-plugin -j 6 \"\$$@\"" >> $(PREFIX)/bin/bld
	@mkdir -p $(PREFIX)/share/opa/bld
	@$(INSTALL) build/gen_myocamlbuild.sh build/myocamlbuild_*fix.ml config.sh config.mli config.ml\
	  $(PREFIX)/share/opa/bld

# Install an opa wrapper with different stdlib and options (for some backwards-compatibility)
install-qmlflat: # depends on opabsl_for_compiler, but we don't want to run ocamlbuild twice
	@mkdir -p $(PREFIX)/bin $(PREFIX)/share/opa/mlstatebsl
	@$(INSTALL) $(BUILD_DIR)/opabsl/mlstatebsl/opabslgen_*.opa $(PREFIX)/share/opa/mlstatebsl
	@echo "#!/bin/bash -ue" > $(PREFIX)/bin/qmlflat
	@chmod 755 $(PREFIX)/bin/qmlflat
	@echo 'exec opa --no-stdlib --no-server --no-cps --no-closure --no-ei --no-constant-sharing --no-undot --separated off --value-restriction disabled --no-warn duplicateL0  --no-warn typer.warncoerce --no-warn unused --no-discard-of-unused-stdlib --no-warn pattern $$(if ! grep -qE "(^| )--no-stdlib( |$$)" <<<"$$*"; then echo $(shell sed "s%^[^# ]\+%$(PREFIX)/share/opa/mlstatebsl/opabslgen_&%; t OK; d; :OK" opabsl/mlstatebsl/bsl-sources); fi) "$$@"' \
	>> $(PREFIX)/bin/qmlflat

# installs some dev tools on top of the normal install; these should not change often
install-all: install install-bld install-qmlflat utils/maxmem
	@$(INSTALL) platform_helper.sh $(PREFIX)/bin/
	@$(INSTALL) utils/maxmem $(PREFIX)/bin/
	@rm utils/maxmem
	@$(INSTALL) utils/plotmem $(PREFIX)/bin/

##
## DOCUMENTATION
##
# (in this section, multiple calls to ocamlbuild are tolerated)

.PHONY: doc.jsbsl
doc.jsbsl: $(MYOCAMLBUILD)
	$(OCAMLBUILD) $@/index.html

# this rules provides the doc.html target (from Makefile.bld)
# the sed are just there to help sorting by filename-within-directory
.PHONY: doc.odocl
doc.odocl:
	echo $(foreach lib,$(ALL_LIBS),$(lib-cmi-$(lib):%.cmi=%)) \
	| sed 's# \+#\n#g' \
	| sed 's#\(.*\)/\([^/]*\)#\1 \2#' \
	| sort -k 2 -u \
	| sed 's#\(.*\) \([^ ]*\)#\1/\2#' \
	>$@

.PHONY: packages-api
packages-api: $(MYOCAMLBUILD)
	OPAOPT="$(OPAOPT) --rebuild --api" $(OCAMLBUILD) opa-packages.stamp

.PHONY: opadoc/doc
opadoc/doc: opadoc packages-api
	@mkdir -p $(BUILD_DIR)/$@
	$(BUILD_DIR)/bin/opadoc -o $(BUILD_DIR)/$@ $(BUILD_DIR)/stdlib

.PHONY: book
book:
	$(MAKE) -C doc/book

.PHONY: examples
examples: $(MYOCAMLBUILD)
	$(OCAMLBUILD) $(call target-tools,opa-bin opa-plugin-builder-bin) opa-packages.stamp
	$(call copy-tools,opa-bin opa-plugin-builder-bin)
	MLSTATELIBS=`pwd`/$(BUILD_DIR) \
	OPA="`pwd`/$(BUILD_DIR)/lib/opa/bin/opa-bin -I `pwd`/$(BUILD_DIR)" \
	OPA_PLUGIN_BUILDER=`pwd`/$(BUILD_DIR)/lib/opa/bin/opa-plugin-builder-bin \
	$(MAKE) -C doc/book examples

.PHONY: book-clean
book-clean:
	$(MAKE) -C doc/book clean

.PHONY: clean
clean: book-clean

.PHONY: doc
doc: doc.html opadoc/doc book
