Client-server distribution
~~~~~~~~~~~~~~~~~~~~~~~~~~

[[slicer]]
// .About this section
// ***********************
// This section details the distribution between client and server, including:

// - the rules for client/server slicing;
// - the semantics of serialization client <-> server serialization;
// - the semantics of (dis)connexion;
// - the semantics of garbage-collection;
// - caching;
// - best practices.
// ***********************
This section details the distribution between client and server.

//////////////////////////////////////////////////////
// Main editor for this section: Valentin Gatien-Baron
//////////////////////////////////////////////////////

//////////////////////////////////////////////////////
// If an item spans several sections, please provide
// hyperlinks, e.g. type definitions have both a syntax
// and a more complete definition on the corresponding
// section
//////////////////////////////////////////////////////

//////////////////////////////////////////////////////
// If an item is considered experimental and may or may
// not survive to future versions, please label it using
// an Admonition block with style [CAUTION]
//////////////////////////////////////////////////////

Slicing
^^^^^^^

Opa is a language that can be executed both on the client and on the server,
but at some point during the compilation process, it must be decided on which
side does the code actually ends up, and where there are remote calls.

This is the job of the slicer.

The slicer can put each toplevel declaration (or component of a toplevel module)
either on the server, or on the client, or on both sides.
The slicer will not divide the code at a finer granularity.

The slicer can be told where a declaration should end up with the slicing annotations:

@server::
The declaration is on the server (but it does not mean that it will not be visible by the  client)
@client::
The declaration is on the client (but it does not mean that it will not be visible by the  server)
@both::
The declaration is on both sides.
Because a declaration can do arbitrary side effects, there are two possible meanings:
* Either the side effect is executed on both sides
* Or the side effect is executed once (on the server) and the resulting value is shared
  between the two sides.
+
By default, the slicer duplicate some side effects (printing for instance) and avoids
to duplicate allocation of mutable structures.
// and reading of the global state (like getting the current time).
For instance:
+
[source,opa]
----------------
do println("Hello")
----------------
+
will print "Hello" at toplevel on both sides.
On the other hand
+
[source,opa]
----------------
s = Session.make(...)
----------------
+
will create one unique session shared between the client and the server.

@both_implem::
This directive behaves the same way as +@both+, except that it explicitely
forces the slicer to duplicate the declaration on both sides:
+
[source,opa]
----------------
@both_implem s = Session.make(...)
----------------
+
This will create a session at the startup of the server and a session in each client.

Slicing annotations are not mandatory.
When they are left out, the slicer decides where to place declarations: on both
sides whenever it is possible, or on the only possible side when it has to.

When a slicing annotation is put on a (toplevel) module, it becomes the default slicing annotation
for its components (and can be overriden by annotating the component with another annotation).

Now since everything cannot be executed on both sides, there are additional rules. +
Primitives that are defined on one side can only be placed on this side. +
When a primitive is server only, not only it is placed on the server, but it is implicitely tagged
as server private, with the consequences explained below.

Whenever a declaration is tagged as server private, it cannot be called by the client
(it is a slicing error), and any declaration using the current declaration becomes
server private itself. +
Since the tag server private propagate, there is a directive to stop the propagation:
it essentially says that a declaration is now visible by the client (possibly after some
authentication mechanism, checking the input, or simply because you have a server only
primitive that does not really need to be private to begin with). +
Note that a declaration that is server private can not be called by the client but can nevertheless
call the client.

The relevant directives are:

@publish::
Stops the propagation of the server private tags.
Note that the declaration annotated as +@publish+ are *not* the only entry point of the server:
+
[source,opa]
----------------
@server f(x) = x
----------------
+
+f+ can be called from the client.

@server_private::
Initially, the only declarations that are tagged server private are the one
containing server only primitives. This directive allows to tag some more
declarations.

Finally, sometimes you will want to have a different behaviour on the server and on the client.
This can be done, fairly simply, with +@sliced_expr+:
[source,opa]
----------------
side = @sliced_expr({server="server"; client="client"})
do println(side)
----------------
This will print "server" on the server and "client" on the client.

@sliced_expr::
This is simply a static switch between client and server.
It can appear at any place in an expression.

[WARNING]
The dependencies of the code are not analysed. As a consequence, trying to call
the client from the server at the toplevel will slice correctly but will generate
a runtime error (because there is no client yet, the server has not even been
started yet).

Serialization
^^^^^^^^^^^^^
Any native opa value can be serialized: integers, floats, strings, records and functions.

Naturally, integers, floats, strings and records are copied when they are send
to the other side. Since these structure are not mutable, this duplication is not
observable.
//Integers, floats and strings and records will be copied.

Function serialization can be done in two ways:

* either the side receiving the serialized function builds a function that will make the remote call when applied
* or the side receiving the serialized function actually already has this function in its code
  and can call the local function instead of the remote function

The only remaining types are external types. +
External types are not really serialized unless explicit serialization/deserialization
functions are defined (with <<web_binding_directives,@serializer>>). +
The default serialization generates an identifier and sends this identifier instead.
When the side that generated the identifier unserializes it, it puts back the original
structure in its place. +
The only thing that is not possible in this design is to manipulate an external
type from a side where it was not created. As a consequence, if an external type
can be manipulated by primitives from both sides, then explicit serialization
and deserialization functions *must* be given.

//Flow of control and remote call
//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// il faut présenter le publish_async
// il faut aussi dire que les appels client->server sont bloquants
// sauf ceux qui sont publish async
// même comme ça, on a un seul flot sur le server apparemment donc
// l'éxecution reste sequentielle sur le server
