########################################
# USER VARIABLES
EXE =
PACKNAME = opace.opx
SRC = ace.opa
PCK =
PCKDIR =
PLUGIN = ace.opp
PLUGINDIR = plugin

#Compiler variables
OPACOMPILER = opa
FLAG =

PORT = 8080

include Makefile.common