opadoc
~~~~~~

This executable is a documentation generator for OPA projects.
It reads special comments from OPA files documenting functions and type declarations,
and produces various formats of output (html, man pages, etc.)

Arguments, input
^^^^^^^^^^^^^^^^

The documentation is generated from

* _opa_ files documented with special comments using the _opadoc_ syntax
* _api_ files generated by _opa --api_, containing inferred type informations

The tool parses all the given files, computes an association between types and comments,
then generates a full documention.

Argument should be :

* opa files directly ;
* directories containing opa files

[CAUTION]
_api_ files are not given in the command line of _opadoc_, but found automatically near _opa_ files
or in the given directories

Output
^^^^^^

Formats of output can be specified. Currently, only an _html_ mode is implemented.
Contributions to support more formats are welcome.

At the end of the file analysis and association (_opa + api_) it is possible to store
the result of this association, in an _apix_ file

html
++++

A directory is generated containing several html files, with a list of types, values,
packages, etc.

Options
^^^^^^^
[width="90%",cols="3",frame="topbot",options="header"]
|========================================================
| option | argument | description
| --output-dir, -o | <dir> |
Specify an Output directory where to put the generated documentation. The default value is 'doc'
| --private | none |
Export private and abstract types/values. This option can be used during e.g. the co-developpement of
a package, internally. Note that the documentation of the stdlib in the distribution of OPA is
not compiled with this option.
|========================================================

Example
^^^^^^^

-------------------------
user@computer:~/$ ls
bar  foo.opa

user@computer:~/$ ls bar
bar.opa

user@computer:~/$ opa --api bar/bar.opa foo.opa

user@computer:~/$ ls
bar  foo.api  foo.opa  foo.exe

user@computer:~/$ ls bar
bar.api  bar.opa

user@computer:~/$ opadoc foo.opa bar -o doc

user@computer:~/$ open doc/index.html
-------------------------


Common errors
^^^^^^^^^^^^^

TODO

Syntax of comments
^^^^^^^^^^^^^^^^^^

TODO
