# =================================================== #
#    LIBBSL : introspection & runtime library         #
#             BYPASS STANDARD LIBRARY                 #
# =================================================== #

# Mathieu Barbin - Mehdi Bouaziz

# This makefile is just here for test

# DOCUMENTATION : Goto manual/  

test : 
	make -C tests all

clean :
	make -C tests clean
