#!/bin/sh -e

#
# MacOS X version
#

MLSTATELIBS=/opt/mlstate
PREFIX=/usr/local

remove() {
    if ! [ $(ls -al "$PREFIX/bin/$1" 2>/dev/null | grep "$MLSTATELIBS" | wc -l) -eq 0 ]; then
	echo "Removing $PREFIX/bin/$1"
	sudo rm "$PREFIX/bin/$1"
    fi
}

logger -t "OPA" "Postinstall starting"

logger -t "OPA" "Removing deprecated tools"

remove "ofile"
remove "odeplink"
remove "odep"
remove "ocamlbase.top"
remove "ocamlbase"
remove "mlstate_platform"
remove "mlidl"
remove "jsstat"
remove "genproto"
remove "genman.native" # keep me, historic reason
remove "genman"
remove "gen_opatop_manpage"
remove "gen_opa_manpage"
remove "filepos"
remove "bslbrowser"
remove "wsdl2ml"
remove "trx_interpreter"
remove "trx"
remove "qmljs"
remove "ppjs"
remove "ppdebug-opa"
remove "ppdebug"
remove "passdesign"
remove "opatrack"
remove "opadep"
remove "opa2opa"

remove "opatop"
remove "opadoc"
remove "opa-db-tool"
remove "opa-db-server"

logger -t "OPA" "Postinstall complete"
