########################################
# USER VARIABLES
EXE = main.exe
PACKNAME = main.opx
SRC = src/main.opa src/page.opa src/users.opa
PCK = opace.opx
PCKDIR = ./
PLUGIN =
PLUGINDIR =

#Compiler variables
OPACOMPILER = opa.exe
FLAG =
OPADOC = opadoc-gen.exe
PORT = 9000

include Makefile.common