#!/bin/bash

P=$PWD
DIRS="opa_binding_examples hello_chat hello_recaptcha hello_web_services hello_wiki hello-opa"

for DIR in $DIRS; do
    LOG=/tmp/opageneral-git-$(basename $DIR)-$TMP
    printf "[33m============================== In %-15s ==============================[0m\n" $DIR >$LOG
    cd $P/$DIR && git "$@" >>$LOG 2>&1 &
done

j=0
for DIR in $DIRS; do
    j=$((j+1))
    LOG=/tmp/opageneral-git-$(basename $DIR)-$TMP
    PID=$(jobs -p $j 2>/dev/null)
    if [ $? -eq 0 ]; then
        tail -q -n +0 -f $LOG  --pid=$PID
    else
        cat $LOG
    fi
    rm -f $LOG
done
